#!/bin/bash

ST_SRC="\033[34m"
ST_PASS="\033[32m"
ST_FAIL="\033[31m"
ST_RST="\033[0m"

sources=$(ls *.mod)

for source in $sources;
do
	echo -e "---- Running test for $ST_SRC $source $ST_RST ----"

	expected="tests/$source.expected"
	actual="tests/$source.actual"

	if [ ! -f $expected ]; then 
		echo "File '$expected' not found."
		echo -e "---- Test $ST_SRC $source $ST_RST skipped ----"
		echo; echo; echo;
		continue
	fi

	make -s
	if [ $? -ne 0 ]; then 
		exit $?
	fi

	./modula < $source > $actual

	diff --color $actual $expected 

	if [ $? -eq 0 ]; then 
		echo -e "---- Test $ST_SRC $source $ST_PASS passed $ST_RST----"
	else
		echo -e "---- Test $ST_SRC $source $ST_FAIL failed $ST_RST----"
	fi
	echo; echo; echo;
done
